version: 2

jobs:
  
  build:
    working_directory: ~/mritopng
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout

      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      
      - run:
          command: |
            . venv/bin/activate
            nosetests
